//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSE_Reloaded.LocalizedRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageBoxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCSE_Reloaded.LocalizedRes.MessageBoxes", typeof(MessageBoxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此文件已更改，如不保存，您在 {time} 后所做的更改将丢失。是否保存？.
        /// </summary>
        public static string CloseNotSaved {
            get {
                return ResourceManager.GetString("CloseNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先保存后再关机。.
        /// </summary>
        public static string CloseWindowsShutdown {
            get {
                return ResourceManager.GetString("CloseWindowsShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编译器未能输出文件。有可能发生错误。.
        /// </summary>
        public static string CompiledNotFound {
            get {
                return ResourceManager.GetString("CompiledNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本为空。请输入一些文本。.
        /// </summary>
        public static string EmptyTextBox {
            get {
                return ResourceManager.GetString("EmptyTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法从命令行解析文件。文件未找到。.
        /// </summary>
        public static string ErrorReadConsoleFile {
            get {
                return ResourceManager.GetString("ErrorReadConsoleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制台错误.
        /// </summary>
        public static string ErrorReadConsoleFileTitle {
            get {
                return ResourceManager.GetString("ErrorReadConsoleFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent Design 的设置需要在重启 {nameShort} 后生效。.
        /// </summary>
        public static string FluentSave {
            get {
                return ResourceManager.GetString("FluentSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  当前正在使用 Fluent Design 中的亚克力特效，在 Windows Forms 中找不到相关文档。请在 文件 -&gt; 设置中关闭。.
        /// </summary>
        public static string FluentWarning {
            get {
                return ResourceManager.GetString("FluentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入网络文件的地址。该文件必须能本地下载（不开启 JS 的浏览器）且为永久链接。.
        /// </summary>
        public static string InputDownload {
            get {
                return ResourceManager.GetString("InputDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件失败。.
        /// </summary>
        public static string InputDownloadFailed {
            get {
                return ResourceManager.GetString("InputDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从网络打开.
        /// </summary>
        public static string InputDownloadTitle {
            get {
                return ResourceManager.GetString("InputDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尚未实现.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试图使用浏览器打开的文件不是 HTML 或 XML 文件。\r\n如果确实是上述文件，请将其后缀名变为对应的后缀名。.
        /// </summary>
        public static string NotMarkup {
            get {
                return ResourceManager.GetString("NotMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节电模式已开启。部分功能会被禁用。.
        /// </summary>
        public static string PowerSavingON {
            get {
                return ResourceManager.GetString("PowerSavingON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在节电模式下不可以打印文件。.
        /// </summary>
        public static string PowerSavingPrint {
            get {
                return ResourceManager.GetString("PowerSavingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您必须先保存文件至少一次。.
        /// </summary>
        public static string PrintNotSaved {
            get {
                return ResourceManager.GetString("PrintNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为.
        /// </summary>
        public static string SaveAsBoxTitle {
            get {
                return ResourceManager.GetString("SaveAsBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从 Web 下载文件.
        /// </summary>
        public static string StatusDownload {
            get {
                return ResourceManager.GetString("StatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 就绪.
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
