// RelaperCrystal's Simple Editor
// Copyright (C) RelaperCrystal and contributors 2020.

/* Classifier 规范
 * #Classifier 开头：等同于声明公开类 Program。
 * #Markings：标记产品。
 * #DefineImport：引用 .NET 命名空间，等同于 using。
 * #End：行尾，等同于 ;。
 * #MainMethod：等同于声明 Main。
 * #EndMainMethod：等同于关闭 Main 方法。
 * #EndClassifier：等同于关闭公开类 Program。
 * 
 * Classifier 转换类如下提供。请先去除 Obsolete。本类不再被编译。
 */


using System;

namespace RCSE_Reloaded.ClassifierLanguage
{
	[Obsolete("Classifier 不再使用。", true)]
	public static class Parser
	{
		public static string ParseToCSharp(string source)
		{
			string result;
			result = ProcessReplace(source);
			result = MethodReplace(result);
			return result;
		}

		private static string ProcessReplace(string source)
		{
			string result;
			result = source.Replace("#Classifier", "public class Program\r\n{");
			result = result.Replace("#Markings", "// Generated by RCSE Classifier");
			result = result.Replace("#DefineImport", "using");
			result = result.Replace("#End", ";");
			result = result.Replace("#MainMethod", "public static void Main(string[] args)\r\n  {");
			result = result.Replace("#EndMainMethod", "    }");
			result = result.Replace("#EndClassifier", "}");
			return result;
		}

		private static string MethodReplace(string source)
		{
			string result;
			result = source.Replace("Print", "Console.WriteLine");
			result = result.Replace("Error", "Console.Error");
			result = result.Replace("PrintCurrentLine", "Console.Write");
			return result;
		}
	}
}
