//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSE_Reloaded.LocalizedRes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCSE_Reloaded.LocalizedRes.Chinese", typeof(Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Compile C# 的本地化字符串。
        /// </summary>
        internal static string BtnCompileCSharp {
            get {
                return ResourceManager.GetString("BtnCompileCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Debug 的本地化字符串。
        /// </summary>
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit 的本地化字符串。
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F&amp;ormat 的本地化字符串。
        /// </summary>
        internal static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Help 的本地化字符串。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About 的本地化字符串。
        /// </summary>
        internal static string MIAbout {
            get {
                return ResourceManager.GetString("MIAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Quit 的本地化字符串。
        /// </summary>
        internal static string MIExit {
            get {
                return ResourceManager.GetString("MIExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New 的本地化字符串。
        /// </summary>
        internal static string MINew {
            get {
                return ResourceManager.GetString("MINew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 O&amp;pen 的本地化字符串。
        /// </summary>
        internal static string MIOpen {
            get {
                return ResourceManager.GetString("MIOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open In Browser 的本地化字符串。
        /// </summary>
        internal static string MIOpenInBrowser {
            get {
                return ResourceManager.GetString("MIOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Print 的本地化字符串。
        /// </summary>
        internal static string MIPrint {
            get {
                return ResourceManager.GetString("MIPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save 的本地化字符串。
        /// </summary>
        internal static string MISave {
            get {
                return ResourceManager.GetString("MISave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S&amp;ave To 的本地化字符串。
        /// </summary>
        internal static string MISaveTo {
            get {
                return ResourceManager.GetString("MISaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string MISettings {
            get {
                return ResourceManager.GetString("MISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string TabDebug {
            get {
                return ResourceManager.GetString("TabDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        internal static string TabToolbox {
            get {
                return ResourceManager.GetString("TabToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licenses 的本地化字符串。
        /// </summary>
        internal static string TILicense {
            get {
                return ResourceManager.GetString("TILicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle (Ready) 的本地化字符串。
        /// </summary>
        internal static string ToolbarReady {
            get {
                return ResourceManager.GetString("ToolbarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string ToolRun {
            get {
                return ResourceManager.GetString("ToolRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string ToolSave {
            get {
                return ResourceManager.GetString("ToolSave", resourceCulture);
            }
        }
    }
}
