//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSE_Reloaded.LocalizedRes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCSE_Reloaded.LocalizedRes.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 编译 C# 的本地化字符串。
        /// </summary>
        internal static string BtnCompileCSharp {
            get {
                return ResourceManager.GetString("BtnCompileCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试(&amp;D) 的本地化字符串。
        /// </summary>
        internal static string MenuDebug {
            get {
                return ResourceManager.GetString("MenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(&amp;E) 的本地化字符串。
        /// </summary>
        internal static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(&amp;F) 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式(&amp;O) 的本地化字符串。
        /// </summary>
        internal static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(&amp;H) 的本地化字符串。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string MIAbout {
            get {
                return ResourceManager.GetString("MIAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(&amp;Q) 的本地化字符串。
        /// </summary>
        internal static string MIExit {
            get {
                return ResourceManager.GetString("MIExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建(&amp;N) 的本地化字符串。
        /// </summary>
        internal static string MINew {
            get {
                return ResourceManager.GetString("MINew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string MIOpen {
            get {
                return ResourceManager.GetString("MIOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在浏览器中打开... 的本地化字符串。
        /// </summary>
        internal static string MIOpenInBrowser {
            get {
                return ResourceManager.GetString("MIOpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(&amp;P) 的本地化字符串。
        /// </summary>
        internal static string MIPrint {
            get {
                return ResourceManager.GetString("MIPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存(&amp;S) 的本地化字符串。
        /// </summary>
        internal static string MISave {
            get {
                return ResourceManager.GetString("MISave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为(&amp;A) 的本地化字符串。
        /// </summary>
        internal static string MISaveTo {
            get {
                return ResourceManager.GetString("MISaveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MISettings {
            get {
                return ResourceManager.GetString("MISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     RCSE-Reloaded Code Editor
        ///    Copyright (C) 2018-2020  RelaperCrystal
        ///
        ///    This program is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    This program is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///    MERCHANTABILITY or FITNESS FOR  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SimpleEditor_License {
            get {
                return ResourceManager.GetString("SimpleEditor_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        internal static string TabDebug {
            get {
                return ResourceManager.GetString("TabDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        internal static string TabToolbox {
            get {
                return ResourceManager.GetString("TabToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 许可证 的本地化字符串。
        /// </summary>
        internal static string TILicense {
            get {
                return ResourceManager.GetString("TILicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        internal static string ToolbarReady {
            get {
                return ResourceManager.GetString("ToolbarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string ToolRun {
            get {
                return ResourceManager.GetString("ToolRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string ToolSave {
            get {
                return ResourceManager.GetString("ToolSave", resourceCulture);
            }
        }
    }
}
