//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCSE_Reloaded.LocalizedRes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageBoxes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCSE_Reloaded.LocalizedRes.MessageBoxes", typeof(MessageBoxes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 此文件已更改，如不保存，您在 {time} 后所做的更改将丢失。是否保存？ 的本地化字符串。
        /// </summary>
        public static string CloseNotSaved {
            get {
                return ResourceManager.GetString("CloseNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先保存后再关机。 的本地化字符串。
        /// </summary>
        public static string CloseWindowsShutdown {
            get {
                return ResourceManager.GetString("CloseWindowsShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编译器未能输出文件。有可能发生错误。 的本地化字符串。
        /// </summary>
        public static string CompiledNotFound {
            get {
                return ResourceManager.GetString("CompiledNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本为空。请输入一些文本。 的本地化字符串。
        /// </summary>
        public static string EmptyTextBox {
            get {
                return ResourceManager.GetString("EmptyTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fluent Design 的设置需要在重启 {nameShort} 后生效。 的本地化字符串。
        /// </summary>
        public static string FluentSave {
            get {
                return ResourceManager.GetString("FluentSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  当前正在使用 Fluent Design 中的亚克力特效，在 Windows Forms 中找不到相关文档。请在 文件 -&gt; 设置中关闭。 的本地化字符串。
        /// </summary>
        public static string FluentWarning {
            get {
                return ResourceManager.GetString("FluentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入网络文件的地址。该文件必须能本地下载（不开启 JS 的浏览器）且为永久链接。 的本地化字符串。
        /// </summary>
        public static string InputDownload {
            get {
                return ResourceManager.GetString("InputDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件失败。 的本地化字符串。
        /// </summary>
        public static string InputDownloadFailed {
            get {
                return ResourceManager.GetString("InputDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从网络打开 的本地化字符串。
        /// </summary>
        public static string InputDownloadTitle {
            get {
                return ResourceManager.GetString("InputDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未实现 的本地化字符串。
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试图使用浏览器打开的文件不是 HTML 或 XML 文件。\r\n如果确实是上述文件，请将其后缀名变为对应的后缀名。 的本地化字符串。
        /// </summary>
        public static string NotMarkup {
            get {
                return ResourceManager.GetString("NotMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节电模式已开启。部分功能会被禁用。 的本地化字符串。
        /// </summary>
        public static string PowerSavingON {
            get {
                return ResourceManager.GetString("PowerSavingON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在节电模式下不可以打印文件。 的本地化字符串。
        /// </summary>
        public static string PowerSavingPrint {
            get {
                return ResourceManager.GetString("PowerSavingPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您必须先保存文件至少一次。 的本地化字符串。
        /// </summary>
        public static string PrintNotSaved {
            get {
                return ResourceManager.GetString("PrintNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        public static string SaveAsBoxTitle {
            get {
                return ResourceManager.GetString("SaveAsBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 Web 下载文件 的本地化字符串。
        /// </summary>
        public static string StatusDownload {
            get {
                return ResourceManager.GetString("StatusDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
    }
}
